# fly.toml app configuration file generated for pencil-editor on 2026-06-10T00:33:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pencil-editor'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3001'
  INKLY_API_HOST = '0.0.0.0'
  INKLY_API_STATIC_ROOT = './dist'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    method = 'get'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
