import { existsSync, watch } from 'node:fs'
import { lstat, mkdir, mkdtemp, rename, rm, rmdir, writeFile } from 'node:fs/promises'
import {
  basename,
  dirname,
  extname,
  isAbsolute,
  join,
  posix,
  relative,
  resolve,
  sep
} from 'node:path'

import { BUILTIN_IO_FORMATS, IORegistry } from '@open-pencil/core/io'
import {
  exportStorybook,
  STORYBOOK_FRAMEWORKS,
  type StorybookFile,
  type StorybookFramework
} from '@open-pencil/dom-css'

import { requireFile } from '#cli/app-client'
import { applyExportFontPolicy } from '#cli/commands/export/font-policy'
import { ok, printError } from '#cli/format'
import { loadDocument, populateWholeDocument, requirePage } from '#cli/headless'

import { readManifest, writeManifest, type StoryManifest, type StoryOwner } from './manifest'

interface StorybookArgs {
  file?: string
  output?: string
  page?: string
  node?: string
  framework: string
  'design-images': boolean
  'font-policy': string
  watch?: boolean
}

const io = new IORegistry(BUILTIN_IO_FORMATS)

function isStorybookFramework(value: string): value is StorybookFramework {
  return STORYBOOK_FRAMEWORKS.some((framework) => framework === value)
}

function toPosix(path: string): string {
  return path.split(sep).join(posix.sep)
}

/** Repository-relative path for `openpencil://` links, when the file sits under the cwd. */
function linkPath(file: string): string | undefined {
  const path = toPosix(relative(process.cwd(), resolve(file)))
  return path.startsWith('../') || isAbsolute(path) ? undefined : path
}

/** What an export replaces: every page of `source`, or only `page` for a one-page export. */
interface ExportScope {
  source: string
  page?: string
}

function owns(scope: ExportScope, owner: StoryOwner): boolean {
  return owner.source === scope.source && (scope.page === undefined || owner.page === scope.page)
}

function conflict(outputDir: string, path: string, manifest: StoryManifest, scope: ExportScope) {
  const target = join(outputDir, path)
  const elsewhere = `; export ${scope.source} to another --output directory.`
  if (!Object.hasOwn(manifest.files, path))
    return new Error(`${target} was not generated by this export${elsewhere}`)
  const owner = manifest.files[path]
  if (owner.source === scope.source)
    return new Error(
      `${target} holds page ${owner.page} of ${scope.source}; export the whole document to renumber its stories.`
    )
  return new Error(`${target} was generated from ${owner.source}, page ${owner.page}${elsewhere}`)
}

function isErrorCode(error: unknown, ...codes: string[]): boolean {
  return error instanceof Error && 'code' in error && codes.includes(String(error.code))
}

/**
 * Refuses a path whose `.design` folder is a symbolic link: removing or writing an image
 * through it would reach outside the output directory.
 */
async function refuseLinkedFolder(outputDir: string, path: string): Promise<void> {
  const folder = dirname(path)
  if (folder === '.') return
  const stats = await lstat(join(outputDir, folder)).catch((error: unknown) => {
    if (isErrorCode(error, 'ENOENT')) return null
    throw error
  })
  if (stats && !stats.isDirectory())
    throw new Error(`${join(outputDir, folder)} is not a folder; remove it and export again.`)
}

/**
 * Removes the files the manifest says a previous export of this scope generated, so a
 * component deleted or renamed in the document does not linger, and returns the manifest
 * for the new files. Refuses before removing anything when the export would overwrite a
 * file it did not generate: a hand-written story, another document's, or someone's image.
 */
async function replaceGeneratedFiles(
  outputDir: string,
  scope: ExportScope,
  files: StorybookFile[]
): Promise<StoryManifest> {
  const manifest = await readManifest(outputDir)
  const owned = new Set(
    Object.entries(manifest.files)
      .filter(([, owner]) => owns(scope, owner))
      .map(([path]) => path)
  )
  const paths = files.map((file) => file.path)

  for (const path of new Set([...paths, ...owned])) await refuseLinkedFolder(outputDir, path)
  for (const path of paths) {
    if (owned.has(path) || !existsSync(join(outputDir, path))) continue
    throw conflict(outputDir, path, manifest, scope)
  }
  for (const path of owned) await rm(join(outputDir, path), { force: true })
  for (const folder of new Set([...owned].map(dirname))) {
    if (folder === '.') continue
    // Only a folder the removal emptied goes; anything else someone put there stays.
    await rmdir(join(outputDir, folder)).catch((error: unknown) => {
      if (!isErrorCode(error, 'ENOTEMPTY', 'ENOENT', 'EEXIST')) throw error
    })
  }

  const kept = Object.entries(manifest.files).filter(([path]) => !owned.has(path))
  const added = files.map((file) => [file.path, { source: scope.source, page: file.page }])
  return { version: 1, files: Object.fromEntries([...kept, ...added]) }
}

async function writeStories(
  args: StorybookArgs,
  file: string,
  framework: StorybookFramework,
  outputDir: string
): Promise<number> {
  const graph = await loadDocument(file)
  const pageId = args.page ? requirePage(graph, args.page).id : undefined
  populateWholeDocument(graph)
  if (args['design-images']) {
    const pageIds = pageId ? [pageId] : graph.getPages().map((page) => page.id)
    await applyExportFontPolicy(graph, pageIds, 'PNG', args['font-policy'])
  }
  const files = await exportStorybook(graph, {
    framework,
    pageId,
    linkPath: linkPath(file),
    renderDesignImage: args['design-images']
      ? async (nodeId) => {
          const result = await io.exportContent(
            'png',
            { graph, target: { scope: 'node', nodeId } },
            { format: 'PNG', scale: 2 }
          )
          if (!(result.data instanceof Uint8Array)) throw new Error('PNG export returned text.')
          return result.data
        }
      : undefined
  })
  if (files.length === 0)
    throw new Error(`No components found in ${args.page ? `page "${args.page}"` : 'the document'}.`)

  // Relative to the output, the document's path is the same on every machine and cwd.
  const scope = { source: toPosix(relative(outputDir, resolve(file))), page: args.page }
  await mkdir(outputDir, { recursive: true })
  // Staged next to the output so a failed write leaves the previous export in place,
  // and in a dot folder, which Storybook's story globs skip.
  const staging = await mkdtemp(join(outputDir, '.openpencil-export-'))
  try {
    for (const story of files) {
      await mkdir(dirname(join(staging, story.path)), { recursive: true })
      await writeFile(join(staging, story.path), story.content)
    }
    const manifest = await replaceGeneratedFiles(outputDir, scope, files)
    for (const { path } of files) {
      await mkdir(dirname(join(outputDir, path)), { recursive: true })
      await rename(join(staging, path), join(outputDir, path))
    }
    await writeManifest(outputDir, manifest)
  } finally {
    await rm(staging, { recursive: true, force: true })
  }
  return files.filter((story) => story.path.endsWith('.stories.ts')).length
}

/** Re-exports on every save; editors that save by rename are why the folder is watched. */
function watchDocument(file: string, onChange: () => Promise<void>): void {
  let timer: ReturnType<typeof setTimeout> | undefined
  let running = Promise.resolve()
  watch(dirname(resolve(file)), (_event, name) => {
    if (name !== basename(file)) return
    clearTimeout(timer)
    timer = setTimeout(() => {
      running = running.then(onChange)
    }, 200)
  })
}

export async function exportStorybookFromFile(args: StorybookArgs): Promise<void> {
  if (args.node) {
    printError('--node is not supported for Storybook export. Use --page to limit it to one page.')
    process.exit(1)
  }
  const framework = args.framework
  if (!isStorybookFramework(framework)) {
    printError(
      `Invalid Storybook framework "${framework}". Use ${STORYBOOK_FRAMEWORKS.join(', ')}.`
    )
    process.exit(1)
  }
  const file = requireFile(args.file)
  const outputDir = resolve(args.output ?? `${basename(file, extname(file))}-stories`)
  const run = async () => {
    const count = await writeStories(args, file, framework, outputDir)
    console.log(ok(`Exported ${count} story files to ${outputDir}`))
  }

  try {
    await run()
  } catch (error) {
    printError(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
  if (!args.watch) return

  // A save can land mid-write or break the document; report it and keep watching.
  watchDocument(file, () =>
    run().catch((error: unknown) =>
      printError(error instanceof Error ? error.message : String(error))
    )
  )
  console.log(ok(`Watching ${file} for changes`))
}
