import dedent from 'dedent'
import { compact } from 'es-toolkit/array'

import { es } from '@open-pencil/emit'

import type { ComponentModel, GeneratedKind } from '../components/model'
import { claimName, identifierName } from './names'

/** Tells readers the file is generated; nothing parses it. */
const HEADER = '// Generated by OpenPencil. Re-export to update; edits are overwritten.'

const MODULE = es.parseModule(dedent`
  import type { Meta, StoryObj } from '@storybook/vue3-vite'
  import { expect } from 'storybook/test'

  import $Component from '$path'

  const meta = {
    title: $title,
    component: $Component,
    parameters: $parameters,
    args: $args,
    argTypes: $argTypes
  } satisfies Meta<typeof $Component>

  export default meta
  type Story = StoryObj<typeof meta>
`)

const STORY = es.parseModule(`export const $name: Story = $story`)

/**
 * What clicking a control does, as Reka marks it: the role to find it by, the element that
 * changes, and the `data-state` it ends in.
 */
const INTERACTIONS: Partial<Record<GeneratedKind, { role: string; state: string }>> = {
  switch: { role: 'switch', state: 'checked' },
  checkbox: { role: 'checkbox', state: 'checked' },
  toggle: { role: 'button', state: 'on' },
  collapsible: { role: 'button', state: 'open' }
}

const PLAY = es.parseExpression(dedent`
  async ({ canvas, userEvent }) => {
    const control = canvas.getByRole($role)
    await userEvent.click(control)
    await expect(control).toHaveAttribute('data-state', $state)
  }
`)

export interface ComponentStoriesData {
  title: string
  component: ComponentModel
  /** The component's import path next to the stories, such as `./Switch.vue`. */
  path: string
  /** Design links for the whole file, as `parameters.design` entries. */
  design: { name: string; type: string; url: string }[]
}

const FALSE = es.parseExpression('false')
const TRUE = es.parseExpression('true')

function restArgs(component: ComponentModel): [string, es.SyntaxNode][] {
  return [
    ...(component.model ? [[component.model, FALSE] as [string, es.SyntaxNode]] : []),
    ...(component.disabled ? [['disabled', FALSE] as [string, es.SyntaxNode]] : []),
    ...component.props.map((prop): [string, es.SyntaxNode] => [prop.name, es.string(prop.default)])
  ]
}

function argTypes(component: ComponentModel): es.SyntaxNode {
  const boolean = es.object([['control', es.string('boolean')]])
  return es.object([
    ...(component.model ? [[component.model, boolean] as [string, es.SyntaxNode]] : []),
    ...(component.disabled ? [['disabled', boolean] as [string, es.SyntaxNode]] : []),
    ...component.props.map((prop): [string, es.SyntaxNode] => [
      prop.name,
      es.object([
        ['control', es.string('select')],
        ['options', es.array(prop.options.map(es.string))]
      ])
    ])
  ])
}

/** A story per state worth seeing: at rest, each boolean on, disabled, and each prop value. */
function stories(component: ComponentModel): { name: string; story: es.SyntaxNode }[] {
  const taken = new Set<string>()
  const story = (label: string, args: [string, es.SyntaxNode][], play?: es.SyntaxNode) => ({
    name: claimName(identifierName(label, 'Story'), taken),
    story: es.object([
      ...(args.length > 0 ? [['args', es.object(args)] as [string, es.SyntaxNode]] : []),
      ...(play ? [['play', play] as [string, es.SyntaxNode]] : [])
    ])
  })
  const interaction = INTERACTIONS[component.kind]
  return [
    story(
      'Default',
      [],
      interaction &&
        es.fill(PLAY, { $role: es.string(interaction.role), $state: es.string(interaction.state) })
    ),
    ...(component.model ? [story(component.model, [[component.model, TRUE]])] : []),
    ...(component.disabled ? [story('Disabled', [['disabled', TRUE]])] : []),
    ...component.props.flatMap((prop) =>
      prop.options
        .filter((option) => option !== prop.default)
        .map((option) => story(option, [[prop.name, es.string(option)]]))
    )
  ]
}

/** CSF3 stories for a generated Vue component, with a play function that operates it. */
export function printComponentStories(data: ComponentStoriesData): string {
  const { component } = data
  const parameters =
    data.design.length > 0
      ? es.object([
          [
            'design',
            es.array(
              data.design.map((entry) =>
                es.object([
                  ['name', es.string(entry.name)],
                  ['type', es.string(entry.type)],
                  ['url', es.string(entry.url)]
                ])
              )
            )
          ]
        ])
      : es.OMIT
  const body = es.fill(MODULE, {
    $Component: es.identifier(component.name),
    $path: es.string(data.path),
    $title: es.string(data.title),
    $parameters: parameters,
    $args: es.object(restArgs(component)),
    $argTypes: argTypes(component)
  }).body
  const exported = stories(component).flatMap(
    (item) => es.fill(STORY, { $name: es.identifier(item.name), $story: item.story }).body
  )
  // Only a control with a play function uses `expect`.
  const [types, expectImport, ...rest] = body
  const imports = INTERACTIONS[component.kind] ? [types, expectImport] : [types]
  const module = es.printModule({
    type: 'Program',
    sourceType: 'module',
    body: compact([...imports, ...rest, ...exported])
  })
  return `${HEADER}\n${module}\n`
}
