import dedent from 'dedent'
import { compact } from 'es-toolkit/array'

import { es } from '@open-pencil/emit'

import type { ComponentModel, GeneratedComponent, GeneratedKind } from '../components/model'
import { claimName, identifierName } from './names'

/** Tells readers the file is generated; nothing parses it. */
const HEADER = '// Generated by OpenPencil. Re-export to update; edits are overwritten.'

const MODULE = es.parseModule(dedent`
  import type { Meta, StoryObj } from '$storybook'
  import { expect } from 'storybook/test'

  const meta = {
    title: $title,
    component: $Component,
    parameters: $parameters,
    args: $args,
    argTypes: $argTypes
  } satisfies Meta<typeof $Component>

  export default meta
  type Story = StoryObj<typeof meta>
`)

const IMPORT_DEFAULT = es.parseModule(`import $Component from '$path'`)
const IMPORT_NAMED = es.parseModule(`import { $Component } from '$path'`)

const STORY = es.parseModule(`export const $name: Story = $story`)

/**
 * What clicking a control does, as Reka marks it: the role to find it by, the element that
 * changes, and the `data-state` it ends in.
 */
const INTERACTIONS: Partial<Record<GeneratedKind, { role: string; state: string }>> = {
  switch: { role: 'switch', state: 'checked' },
  checkbox: { role: 'checkbox', state: 'checked' },
  toggle: { role: 'button', state: 'on' },
  collapsible: { role: 'button', state: 'open' }
}

const PLAY = es.parseExpression(dedent`
  async ({ canvas, userEvent }) => {
    const control = canvas.getByRole($role)
    await userEvent.click(control)
    await expect(control).toHaveAttribute('data-state', $state)
  }
`)

export interface ComponentStoriesData {
  /** The Storybook renderer package the stories import their types from. */
  storybook: string
  title: string
  component: ComponentModel
  generated: Pick<GeneratedComponent, 'entry' | 'valueArg'>
  /** Design links for the whole file, as `parameters.design` entries. */
  design: { name: string; type: string; url: string }[]
}

const FALSE = es.parseExpression('false')
const TRUE = es.parseExpression('true')

/** A model's value at rest: off, the option a choice starts on, or none for an open choice. */
function restValue(component: ComponentModel): es.SyntaxNode | null {
  if (!component.choice) return FALSE
  return component.choice.default === null ? null : es.string(component.choice.default)
}

function restArgs(component: ComponentModel, model: string | null): [string, es.SyntaxNode][] {
  const rest = restValue(component)
  return [
    ...(model && rest ? [[model, rest] as [string, es.SyntaxNode]] : []),
    ...(component.disabled ? [['disabled', FALSE] as [string, es.SyntaxNode]] : []),
    ...component.props.map((prop): [string, es.SyntaxNode] => [prop.name, es.string(prop.default)]),
    ...component.texts.map((text): [string, es.SyntaxNode] => [text.name, es.string(text.default)])
  ]
}

function argTypes(component: ComponentModel, model: string | null): es.SyntaxNode {
  const boolean = es.object([['control', es.string('boolean')]])
  const select = (options: readonly string[]) =>
    es.object([
      ['control', es.string('select')],
      ['options', es.array(options.map(es.string))]
    ])
  const modelControl = component.choice ? select(component.choice.options) : boolean
  return es.object([
    ...(model ? [[model, modelControl] as [string, es.SyntaxNode]] : []),
    ...(component.disabled ? [['disabled', boolean] as [string, es.SyntaxNode]] : []),
    ...component.props.map((prop): [string, es.SyntaxNode] => [prop.name, select(prop.options)]),
    ...component.texts.map((text): [string, es.SyntaxNode] => [
      text.name,
      es.object([['control', es.string('text')]])
    ])
  ])
}

/** A story per state worth seeing: at rest, each boolean on, disabled, and each prop value. */
function stories(
  component: ComponentModel,
  model: string | null
): { name: string; story: es.SyntaxNode }[] {
  const taken = new Set<string>()
  const story = (label: string, args: [string, es.SyntaxNode][], play?: es.SyntaxNode) => ({
    name: claimName(identifierName(label, 'Story'), taken),
    story: es.object([
      ...(args.length > 0 ? [['args', es.object(args)] as [string, es.SyntaxNode]] : []),
      ...(play ? [['play', play] as [string, es.SyntaxNode]] : [])
    ])
  })
  const interaction = INTERACTIONS[component.kind]
  return [
    story(
      'Default',
      [],
      interaction &&
        es.fill(PLAY, { $role: es.string(interaction.role), $state: es.string(interaction.state) })
    ),
    ...(component.model && model && !component.choice
      ? [story(component.model, [[model, TRUE]])]
      : []),
    // A choice gets a story per option it does not start on, such as each other tab.
    ...(component.choice && model
      ? component.choice.options
          .filter((option) => option !== component.choice?.default)
          .map((option) => story(option, [[model, es.string(option)]]))
      : []),
    ...(component.disabled ? [story('Disabled', [['disabled', TRUE]])] : []),
    ...component.props.flatMap((prop) =>
      prop.options
        .filter((option) => option !== prop.default)
        .map((option) => story(option, [[prop.name, es.string(option)]]))
    )
  ]
}

/** CSF3 stories for a generated component, with a play function that operates it. */
export function printComponentStories(data: ComponentStoriesData): string {
  const { component } = data
  const parameters =
    data.design.length > 0
      ? es.object([
          [
            'design',
            es.array(
              data.design.map((entry) =>
                es.object([
                  ['name', es.string(entry.name)],
                  ['type', es.string(entry.type)],
                  ['url', es.string(entry.url)]
                ])
              )
            )
          ]
        ])
      : es.OMIT
  const { entry, valueArg: model } = data.generated
  const body = es.fill(MODULE, {
    $storybook: es.string(data.storybook),
    $Component: es.identifier(component.name),
    $title: es.string(data.title),
    $parameters: parameters,
    $args: es.object(restArgs(component, model)),
    $argTypes: argTypes(component, model)
  }).body
  const componentImport = es.fill(entry.named ? IMPORT_NAMED : IMPORT_DEFAULT, {
    $Component: es.identifier(component.name),
    $path: es.string(entry.path)
  }).body
  const exported = stories(component, model).flatMap(
    (item) => es.fill(STORY, { $name: es.identifier(item.name), $story: item.story }).body
  )
  // Only a control with a play function uses `expect`.
  const [types, expectImport, ...rest] = body
  const imports = INTERACTIONS[component.kind] ? [types, expectImport] : [types]
  const module = es.printModule({
    type: 'Program',
    sourceType: 'module',
    body: compact([...imports, ...componentImport, ...rest, ...exported])
  })
  return `${HEADER}\n${module}\n`
}
