import dedent from 'dedent'

import * as es from './estree'

export const STORYBOOK_FRAMEWORKS = ['react', 'vue', 'html'] as const
export type StorybookFramework = (typeof STORYBOOK_FRAMEWORKS)[number]

/** Tells readers the file is generated; nothing parses it. */
const HEADER = '// Generated by OpenPencil. Re-export to update; edits are overwritten.'

/** Everything a story module varies by; the TypeScript around it is a fixed template. */
export interface StoryModuleData {
  framework: StorybookFramework
  title: string
  /** Group name used in the missing-variant error. */
  name: string
  props: { name: string; options: string[] }[]
  variants: { values: string[]; html: string }[]
  metaDesign: StoryDesign[]
  /** Import path of each design image, by variant index. */
  images: string[]
  stories: { exportName: string; label: string; values: string[]; design: StoryDesign[] }[]
}

export type StoryDesign =
  | { type: 'link'; url: string }
  /** Refers to the design image of the variant with this index. */
  | { type: 'image'; variant: number }

const MODULE = es.parseModule(dedent`
  import type { Meta, StoryObj } from '$storybook'

  type Args = $Args

  const variants: Record<string, string> = $variants

  function variantHTML(args: Args): string {
    const key = JSON.stringify($key)
    const html = variants[key]
    if (html === undefined) throw new Error($missing + key)
    return html
  }

  const meta = {
    title: $title,
    parameters: $parameters,
    args: $args,
    argTypes: $argTypes,
    render: (args) => $render
  } satisfies Meta<Args>

  export default meta
  type Story = StoryObj<Args>
`)

const IMAGE = es.parseModule(`const $name = new URL($path, import.meta.url).href`)
const STORY = es.parseModule(`export const $name: Story = $story`)

const FRAMEWORKS: Record<
  StorybookFramework,
  { storybook: string; imports: es.SyntaxNode[]; render: es.SyntaxNode }
> = {
  react: {
    storybook: '@storybook/react-vite',
    imports: es.parseModule(`import { createElement } from 'react'`).body,
    render: es.parseExpression(
      `createElement('div', { dangerouslySetInnerHTML: { __html: variantHTML(args) } })`
    )
  },
  vue: {
    storybook: '@storybook/vue3-vite',
    imports: es.parseModule(`import { h } from 'vue'`).body,
    render: es.parseExpression(`{ setup: () => () => h('div', { innerHTML: variantHTML(args) }) }`)
  },
  html: {
    storybook: '@storybook/html-vite',
    imports: [],
    render: es.parseExpression('variantHTML(args)')
  }
}

const imageName = (variant: number) => `design${variant}`

function argsObject(data: StoryModuleData, values: string[]): es.SyntaxNode {
  return es.object(data.props.map((prop, i) => [prop.name, es.string(values[i] ?? '')]))
}

function parameters(design: StoryDesign[]): es.SyntaxNode {
  const entries = design.map((entry) =>
    entry.type === 'link'
      ? es.object([
          ['name', es.string('OpenPencil')],
          ['type', es.string('link')],
          ['url', es.string(entry.url)]
        ])
      : es.object([
          ['name', es.string('Design')],
          ['type', es.string('image')],
          ['url', es.identifier(imageName(entry.variant))]
        ])
  )
  return es.object([['design', es.array(entries)]])
}

const NO_ARGS = es.parseType('Record<string, never>')

function argsType(data: StoryModuleData): es.SyntaxNode {
  if (data.props.length === 0) return NO_ARGS
  return es.objectType(data.props.map((prop) => [prop.name, es.stringUnionType(prop.options)]))
}

/** Print a CSF3 story module for one component or component set. */
export function printStoryModule(data: StoryModuleData): string {
  const framework = FRAMEWORKS[data.framework]
  const [storybookImport, ...body] = es.fill(MODULE, {
    $storybook: es.string(framework.storybook),
    $Args: argsType(data),
    $variants: es.object(
      data.variants.map((variant) => [JSON.stringify(variant.values), es.string(variant.html)])
    ),
    $key: es.array(
      data.props.map((prop) => ({
        type: 'MemberExpression',
        object: es.identifier('args'),
        property: es.string(prop.name),
        computed: true,
        optional: false
      }))
    ),
    $missing: es.string(`${data.name} has no variant `),
    $title: es.string(data.title),
    $parameters: data.metaDesign.length > 0 ? parameters(data.metaDesign) : es.OMIT,
    $args: argsObject(data, data.variants[0]?.values ?? []),
    $argTypes: es.object(
      data.props.map((prop) => [
        prop.name,
        es.object([
          ['control', es.string('select')],
          ['options', es.array(prop.options.map(es.string))]
        ])
      ])
    ),
    $render: framework.render
  }).body
  const images = data.images.flatMap(
    (path, i) =>
      es.fill(IMAGE, { $name: es.identifier(imageName(i)), $path: es.string(`./${path}`) }).body
  )
  const stories = data.stories.flatMap(
    (story) =>
      es.fill(STORY, {
        $name: es.identifier(story.exportName),
        $story: es.object([
          ['name', es.string(story.label)],
          ...(story.design.length > 0 ? [['parameters', parameters(story.design)] as const] : []),
          ['args', argsObject(data, story.values)]
        ])
      }).body
  )
  const module = es.printModule({
    type: 'Program',
    sourceType: 'module',
    body: [storybookImport, ...framework.imports, ...images, ...body, ...stories]
  })
  return `${HEADER}\n${module}\n`
}
