#!/usr/bin/env bun
/**
 * Scan src/views/*.vue files for English string literals that look like
 * UI-facing text. The goal is to surface candidates for i18n migration,
 * not to be exhaustive — heuristics aim for "obvious to a translator".
 *
 * Heuristics:
 *   - Take text between `>` and `<` inside the <template> block.
 *   - Take `placeholder`, `aria-label`, `:aria-label`, `title` attribute string literals.
 *   - Skip values that are pure punctuation, single characters, numbers, or template expressions.
 *   - Skip text that already references `{{ ... }}` interpolation.
 *
 * Output: markdown table with per-file counts and per-file sample list.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const VIEWS_DIR = 'src/views'
const OUTPUT = 'docs/i18n-audit.md'

interface FileReport {
  file: string
  count: number
  samples: string[]
}

function extractTemplateBlock(content: string): string {
  const match = content.match(/<template>([\s\S]*?)<\/template>/)
  return match ? match[1] : ''
}

function looksLikeEnglish(text: string): boolean {
  const trimmed = text.trim()
  if (!trimmed) return false
  if (trimmed.length < 2) return false
  if (/^\d+$/.test(trimmed)) return false
  if (/^[\s\W_]+$/.test(trimmed)) return false
  if (trimmed.startsWith('{{') || trimmed.endsWith('}}')) return false
  if (!/[A-Za-z]/.test(trimmed)) return false
  // Ignore dot-path expressions or JS identifiers
  if (/^[A-Za-z_$][\w$.]*$/.test(trimmed) && !trimmed.includes(' ')) return false
  return true
}

function dedupe(values: string[]): string[] {
  return [...new Set(values.map((v) => v.trim()))]
}

function auditFile(path: string): FileReport {
  const content = readFileSync(path, 'utf8')
  const template = extractTemplateBlock(content)
  const candidates: string[] = []

  // text between > and < at the start of a new line (heuristic for Vue text content)
  for (const match of template.matchAll(/^\s+([A-Z][^<{\n]*?)$/gm)) {
    const text = match[1].trim()
    if (text.length < 4) continue
    if (text.includes('=')) continue
    if (text.includes('class=')) continue
    if (text.includes('@')) continue
    if (text.startsWith(':')) continue
    if (looksLikeEnglish(text)) candidates.push(text)
  }

  // placeholder="..."
  for (const match of template.matchAll(/placeholder="([^"]+)"/g)) {
    if (looksLikeEnglish(match[1])) candidates.push(match[1])
  }

  // aria-label="..." (static)
  for (const match of template.matchAll(/aria-label="([^"]+)"/g)) {
    if (looksLikeEnglish(match[1])) candidates.push(match[1])
  }

  // title="..."
  for (const match of template.matchAll(/(?:^|\s)title="([^"]+)"/g)) {
    if (looksLikeEnglish(match[1])) candidates.push(match[1])
  }

  const unique = dedupe(candidates)
  return { file: path, count: unique.length, samples: unique.slice(0, 12) }
}

function main() {
  const files = readdirSync(VIEWS_DIR)
    .filter((name) => name.endsWith('.vue'))
    .map((name) => join(VIEWS_DIR, name))
    .sort()

  const reports = files.map(auditFile)
  reports.sort((a, b) => b.count - a.count)

  const lines: string[] = []
  lines.push('# View i18n hardcode audit')
  lines.push('')
  lines.push(
    `Auto-generated by \`bun scripts/i18n/audit-views.ts\`. Counts are heuristic candidates inside <template>, not exact.`
  )
  lines.push('')

  lines.push('| File | Hardcoded candidates | First samples |')
  lines.push('|---|---|---|')
  for (const report of reports) {
    const rel = report.file.replace(/^src\/views\//, '')
    const samples = report.samples
      .map((s) => `\`${s.replace(/`/g, '\\`')}\``)
      .join(' / ')
    lines.push(`| ${rel} | ${report.count} | ${samples || '—'} |`)
  }

  lines.push('')
  lines.push('## Next i18n migration priorities')
  lines.push('')
  const topThree = reports.slice(0, 3)
  for (const report of topThree) {
    const rel = report.file.replace(/^src\/views\//, '')
    lines.push(`- ${rel} — ${report.count} candidates`)
  }

  const text = `${lines.join('\n')}\n`
  writeFileSync(OUTPUT, text)
  console.log(`Wrote ${OUTPUT} (${reports.length} files, ${reports.reduce((s, r) => s + r.count, 0)} total candidates)`)
}

main()
