#!/bin/sh
set -eu

chown -R bun:bun \
  /workspace/open-pencil/node_modules \
  /workspace/open-pencil/packages/scene-graph/node_modules \
  /workspace/open-pencil/packages/pen/node_modules \
  /workspace/open-pencil/packages/kiwi/node_modules \
  /workspace/open-pencil/packages/fig/node_modules \
  /workspace/open-pencil/packages/core/node_modules \
  /workspace/open-pencil/packages/dom-css/node_modules \
  /workspace/open-pencil/packages/vue/node_modules \
  /workspace/open-pencil/packages/cli/node_modules \
  /workspace/open-pencil/packages/mcp/node_modules \
  /workspace/open-pencil/packages/docs/node_modules \
  /workspace/open-pencil/tools/docs/node_modules
