export { createPage, createShape, createSlice } from './create/basic'
export { createComponent, createInstance } from './create/components'
export { fetchIconsTool, insertIcon, searchIconsTool } from './create-icons'
export { render } from './create/render'
export { createVector } from './create/vector'
